const ACCOUNTS = [
  // -------- AGED --------

  {
    lot: 1,
    category: "aged",
    year: 2025,
    country: "Vietnam",
    pp: 100,
    playcount: 117,
    playtime: 3,
    rank: "2.2kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 5,
    category: "aged",
    year: 2024,
    country: "Germany",
    pp: 31,
    playcount: 55,
    playtime: 1,
    rank: "2.7kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 7,
    category: "aged",
    year: 2018,
    country: "France",
    pp: 0,
    playcount: 0,
    playtime: 0,
    rank: "",
    mania: false,
    me: false,
    supporter: false,
    notes:
      "stats hidden due to low amount of players in geo (not really france but close)",
  },

  {
    lot: 8,
    category: "aged",
    year: 2023,
    country: "Maldives",
    pp: 10,
    playcount: 0,
    playtime: 0,
    rank: "",
    mania: false,
    me: false,
    supporter: false,
    notes: "stats hidden due to low amount of players in geo",
  },

  {
    lot: 9,
    category: "aged",
    year: 2024,
    country: "United States",
    pp: 0,
    playcount: null,
    playtime: 0,
    rank: "",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 11,
    category: "aged",
    year: 2024,
    country: "Australia",
    pp: 420,
    playcount: 6000,
    playtime: 70,
    rank: "1.5kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 13,
    category: "aged",
    year: 2021,
    country: "Germany",
    pp: 1000,
    playcount: 2000,
    playtime: 40,
    rank: "870k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 14,
    category: "aged",
    year: 2024,
    country: "United Kingdom",
    pp: 350,
    playcount: 500,
    playtime: 15,
    rank: "1.6kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 16,
    category: "aged",
    year: 2023,
    country: "Costa Rica",
    pp: 0,
    playcount: null,
    playtime: 0,
    rank: "",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 17,
    category: "aged",
    year: 2023,
    country: "France",
    pp: 200,
    playcount: 500,
    playtime: 10,
    rank: "2kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 25,
    category: "aged",
    year: 2024,
    country: "Mexico",
    pp: 900,
    playcount: 5000,
    playtime: 60,
    rank: "1kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 26,
    category: "6digit",
    year: 2024,
    country: "Norway",
    pp: 1500,
    playcount: 2500,
    playtime: 0,
    rank: "800k",
    mania: true,
    me: true,
    supporter: false,
    notes: "mania 1.5kpp",
  },

  // -------- 6 DIGIT --------

  {
    lot: 10,
    category: "6digit",
    year: 2021,
    country: "Vietnam",
    pp: 1500,
    playcount: 6000,
    playtime: 50,
    rank: "750k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 12,
    category: "6digit",
    year: 2022,
    country: "Australia",
    pp: 3000,
    playcount: 15000,
    playtime: 250,
    rank: "300k",
    mania: false,
    me: true,
    supporter: false,
    notes: "for aura farming",
  },

  {
    lot: 15,
    category: "6digit",
    year: 2021,
    country: "Malaysia",
    pp: 4000,
    playcount: 40000,
    playtime: 450,
    rank: "200k",
    mania: false,
    me: false,
    supporter: false,
    notes: "goated for tournaments if anything",
  },

  {
    lot: 19,
    category: "6digit",
    year: 2022,
    country: "Thailand",
    pp: 3600,
    playcount: 13000,
    playtime: 200,
    rank: "250k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 20,
    category: "6digit",
    year: 2022,
    country: "Brazil",
    pp: 1600,
    playcount: 9000,
    playtime: 150,
    rank: "700k",
    mania: false,
    me: true,
    supporter: false,
    notes: "",
  },

  {
    lot: 22,
    category: "6digit",
    year: 2021,
    country: "United Kingdom",
    pp: 2000,
    playcount: 5000,
    playtime: 80,
    rank: "580k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 27,
    category: "6digit",
    year: 2022,
    country: "Vietnam",
    pp: 4500,
    playcount: 50000,
    playtime: 1000,
    rank: "160k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  // -------- 5 DIGIT --------

  {
    lot: 6,
    category: "5digit",
    year: 2017,
    country: "France",
    pp: 6000,
    playcount: 45000,
    playtime: 450,
    rank: "70k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 18,
    category: "5digit",
    year: 2019,
    country: "United States",
    pp: 7500,
    playcount: 70000,
    playtime: 1500,
    rank: "35k",
    mania: false,
    me: true,
    supporter: false,
    notes: "",
  },
  
  {
    lot: 23,
    category: "5digit",
    year: 2022,
    country: "Indonesia",
    pp: 6000,
    playcount: 40000,
    playtime: 700,
    rank: "66k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 24,
    category: "5digit",
    year: 2022,
    country: "Japan",
    pp: 5000,
    playcount: 30000,
    playtime: 300,
    rank: "99k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  // -------- MANIA --------

  {
    lot: 4,
    category: "mania",
    year: 2025,
    country: "Colombia",
    pp: 2700,
    playcount: 900,
    playtime: 25,
    rank: "110k",
    mania: true,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 21,
    category: "mania",
    year: 2024,
    country: "Ecuador",
    pp: 6000,
    playcount: 5000,
    playtime: 100,
    rank: "30k",
    mania: true,
    me: false,
    supporter: false,
    notes: "",
  },
];

const SETTINGS = {
  title: "envi64 account list",
  subtitle:
    "most of stats are very rounded, also ask for availability before paying",
  lastUpdated: "2026-06-21",
  contact: "discord @envi64 192387794667175936",
};
