const ACCOUNTS = [
  // -------- AGED --------

  {
    lot: 48,
    category: "aged",
    year: 2021,
    country: "Peru",
    pp: 0,
    playcount: 3,
    playtime: 0,
    rank: "",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 52,
    category: "aged",
    year: 2024,
    country: "France",
    pp: 250,
    playcount: 100,
    playtime: 5,
    rank: "1.5kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 53,
    category: "aged",
    year: 2021,
    country: "Japan",
    pp: 300,
    playcount: 200,
    playtime: 5,
    rank: "1.5kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 55,
    category: "aged",
    year: 2026,
    country: "Netherlands",
    pp: 300,
    playcount: 300,
    playtime: 5,
    rank: "1.5kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 59,
    category: "aged",
    year: 2020,
    country: "Vietnam",
    pp: 400,
    playcount: 1000,
    playtime: 20,
    rank: "1.5kk",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  // -------- 6 DIGIT --------

  {
    lot: 31,
    category: "6digit",
    year: 2020,
    country: "France",
    pp: 1500,
    playcount: 5500,
    playtime: 60,
    rank: "600k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 41,
    category: "6digit",
    year: 2021,
    country: "France",
    pp: 4500,
    playcount: 18000,
    playtime: 250,
    rank: "150k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 54,
    category: "6digit",
    year: 2021,
    country: "Brazil",
    pp: 1000,
    playcount: 3000,
    playtime: 45,
    rank: "800k",
    mania: false,
    me: false,
    supporter: false,
    notes: "",
  },

  // -------- MANIA --------

  {
    lot: 4,
    category: "mania",
    year: 2025,
    country: "Colombia",
    pp: 2500,
    playcount: 1000,
    playtime: 30,
    rank: "100k",
    mania: true,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 30,
    category: "mania",
    year: 2023,
    country: "xx",
    pp: 3500,
    playcount: 400,
    playtime: 15,
    rank: "70k",
    mania: true,
    me: false,
    supporter: false,
    notes: "",
  },

  {
    lot: 43,
    category: "mania",
    year: 2024,
    country: "Asia",
    pp: 8000,
    playcount: 25000,
    playtime: 500,
    rank: "10k",
    mania: true,
    me: false,
    supporter: false,
    notes: "",
  },

];

const SETTINGS = {
  title: "envi64 account list",
  subtitle:
    "most of stats are very rounded, also ask for availability before paying",
  lastUpdated: "2026-08-01",
  contact: "discord @envi64 192387794667175936 / tg @e3nv2",
};
